#pragma once
#ifndef _SOURCEHEAD_H_
#define _SOURCEHEAD_H_
#ifdef WIN32 //linux platform
#define DEXPORT __declspec(dllexport)
#else // unix like
#define DEXPORT __attribute__ ((visibility ("default")))
#endif
extern "C" DEXPORT bool SourceHead_Init(const void* config);
//return the number of particles generated by one initial Co60 reaction
//these particles are stored in array where Particle* pars points to
//each particle's information: Energy(eV), position(cm) in CT coordinate orientation with isocenter as origin
//unit direction vector, and particle type, weight
extern "C" DEXPORT int SourceHead_Sample(const void* rng, const void* pars);
extern "C" DEXPORT void SourceHead_Delete();
extern "C" DEXPORT double SourceHead_BeamOnTime();
extern "C" DEXPORT void SourceHead_GetIsoCenter(double* px, double* py, double* pz);
extern "C" DEXPORT void SourceHead_GetPrescrition(double* pDose, int* fraction);
extern "C" DEXPORT bool SourceHead_ConvertBeams(const char* txtbeams, const char* beamsPath);
extern "C" DEXPORT double SourceHead_Emax();
#endif